<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Diagram</name>
   <tag></tag>
   <elementGuidId>f21a4f4d-c792-4ca4-98ea-97015d918282</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>db-tile-content-container</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ig-dashboard-container&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-6 col-md-4&quot;]/div[1]/div[1]/div[2]/div[1]/div[@class=&quot;db-areatitle-content-padding&quot;]/div[1]/div[1]/div[4]/div[@class=&quot;db-default-tile-container&quot;]/a[1]/div[@class=&quot;db-tile-content-container&quot;]</value>
   </webElementProperties>
</WebElementEntity>
